"" vim configuration

let g:is_posix = 1
set nocompatible
set history=50

" Use UTF-8
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,latin1
setglobal fileencoding=utf-8

" Enable the mouse
set mouse=a

" Theme and coloration
set t_Co=256
" colorscheme wellsokai

set number
set showmode
set ruler

" Activate syntax coloring and indentation
filetype plugin indent on
syntax on

" Indentation settings
set smartindent
set expandtab       " Use spaces for tabs
set tabstop=2
set shiftwidth=2

set backspace=indent,eol,start

" Enable modelines
set modeline
set modelines=5

" Use <C-l> to center the cursor
noremap <C-l> z.
