#!/bin/sh

# Select an alternate editor in case Emacs is not available.
if [ -x "$(command -v vim)" ]; then
    alternate_editor=vim
elif [ -x "$(command -v nano)" ]; then
    alternate_editor=nano
elif [ -x "$(command -v ee)" ]; then
    alternate_editor=ee
else
    alternate_editor=vi
fi

# If Emacs is available, try to connect to the daemon and open a new console
# frame. If it is not started or Emacs is not available, fall back to the
# alternate editor.
if [ -x "$(command -v emacsclient)" ]; then
    emacsclient --tty --alternate-editor $alternate_editor $@
else
    $alternate_editor $@
fi
